import Link from "next/link";
import { listProjects } from "@/lib/project-repository";
import { getUserLeadSummary, listUserLeads, type FollowUpFilter } from "@/lib/leads/service";
export const dynamic = "force-dynamic";
const label = (status: string) => status[0] + status.slice(1).toLowerCase();
export default async function LeadsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const get = (key: string) => typeof params[key] === "string" ? params[key] as string : undefined;
  const filters = { search: get("search"), projectId: get("project"), status: get("status"), followUp: (get("followUp") as FollowUpFilter) || "all", range: (get("range") as "7" | "30" | "all") || "all", sort: (get("sort") as "newest" | "oldest" | "followup") || "newest", page: Number(get("page") || 1) };
  const [{ items, page, pageCount, total }, summary, projects] = await Promise.all([listUserLeads(filters), getUserLeadSummary(), listProjects()]); const now = new Date();
  const query = (nextPage: number) => { const values = new URLSearchParams(); Object.entries({ ...filters, page: nextPage }).forEach(([key, value]) => { if (value && value !== "all" && value !== "newest" && value !== 1) values.set(key, String(value)); }); return `?${values}`; };
  return <section className="mx-auto max-w-6xl px-5 py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Customer messages</p><h1 className="mt-4 text-4xl font-semibold">Leads</h1><p className="mt-2 text-slate-600">{total} total lead{total === 1 ? "" : "s"}</p></div><div className="flex gap-4"><a className="text-sm font-semibold underline" href={`/api/leads/export${query(1)}`}>Export CSV</a><Link className="text-sm font-semibold underline" href="/dashboard">Back to dashboard</Link></div></div>
    <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-5">{["NEW", "CONTACTED", "QUALIFIED", "WON", "LOST"].map((status) => <div className="rounded-xl border p-4" key={status}><p className="text-sm text-slate-500">{label(status)}</p><p className="mt-1 text-2xl font-semibold">{summary[status] ?? 0}</p></div>)}</div>
    <form className="mt-8 grid gap-3 rounded-2xl border p-4 sm:grid-cols-2 lg:grid-cols-6"><input className="rounded border p-2 lg:col-span-2" defaultValue={filters.search} name="search" placeholder="Search name, email, phone, message" /><select className="rounded border p-2" defaultValue={filters.projectId} name="project"><option value="">All projects</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.business.businessName}</option>)}</select><select className="rounded border p-2" defaultValue={filters.status} name="status"><option value="">All statuses</option>{["NEW", "CONTACTED", "QUALIFIED", "WON", "LOST"].map((status) => <option key={status} value={status}>{label(status)}</option>)}</select><select className="rounded border p-2" defaultValue={filters.followUp} name="followUp"><option value="all">All follow-ups</option><option value="upcoming">Upcoming</option><option value="overdue">Overdue</option><option value="none">No follow-up</option></select><select className="rounded border p-2" defaultValue={filters.sort} name="sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="followup">Follow-up soonest</option></select><select className="rounded border p-2" defaultValue={filters.range} name="range"><option value="all">All time</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select><button className="rounded-full bg-slate-900 px-4 py-2 text-sm font-semibold text-white" type="submit">Apply filters</button></form>
    {items.length === 0 ? <p className="mt-10 rounded-2xl border border-dashed p-10 text-center text-slate-600">Your contact form submissions will appear here.</p> : <div className="mt-8 space-y-3">{items.map((lead) => <Link className="block rounded-2xl border p-5 hover:bg-slate-50" href={`/dashboard/leads/${lead.id}`} key={lead.id}><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-semibold">{lead.name}</h2><p className="text-sm text-slate-600">{lead.email} · {lead.project.businessName}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold">{label(lead.status)}</span></div><p className="mt-3 line-clamp-2 text-sm text-slate-700">{lead.message}</p><p className="mt-3 text-xs text-slate-500">{lead.followUpAt ? `${new Date(lead.followUpAt).getTime() < now.getTime() ? "Overdue · " : "Follow-up · "}${new Date(lead.followUpAt).toLocaleString()} · ` : ""}{new Date(lead.createdAt).toLocaleString()}</p></Link>)}</div>}
    {pageCount > 1 && <nav className="mt-8 flex items-center justify-between text-sm"><span>Page {page} of {pageCount}</span><div className="flex gap-3">{page > 1 && <Link className="underline" href={query(page - 1)}>Previous</Link>}{page < pageCount && <Link className="underline" href={query(page + 1)}>Next</Link>}</div></nav>}
  </section>;
}
