import Link from "next/link";
import { getAdminOverview } from "@/lib/project-repository";

export const dynamic = "force-dynamic";

export default async function AdminPage() {
  const overview = await getAdminOverview();
  const cards = [["Users", overview.totalUsers, "/admin/users"], ["All projects", overview.totalProjects, "/admin/projects"], ["Demo / sample sites", overview.totalDemoSites, "/admin/projects?filter=demos"], ["Featured businesses", overview.totalFeaturedBusinesses, "/admin/projects?filter=featured"]] as const;
  return <section className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><p className="eyebrow">Owner console</p><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-semibold">LaunchSite administration</h1><p className="mt-2 text-slate-600">Manage official samples, promoted businesses, and safe account records.</p></div><Link className="rounded-full bg-slate-900 px-5 py-3 text-sm font-semibold text-white" href="/admin/projects/new">Create sample site</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, href]) => <Link className="rounded-2xl border border-slate-200 p-6 transition hover:border-slate-400" href={href} key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></Link>)}</div><div className="mt-10 grid gap-4 md:grid-cols-3"><Link className="rounded-2xl border p-6" href="/admin/projects"><h2 className="text-xl font-semibold">Demo / Sample Sites</h2><p className="mt-2 text-sm text-slate-600">Edit official examples, their media, content, branding, and public-example state.</p></Link><Link className="rounded-2xl border p-6" href="/admin/users"><h2 className="text-xl font-semibold">Users</h2><p className="mt-2 text-sm text-slate-600">Review safe account details and manage roles conservatively.</p></Link><Link className="rounded-2xl border p-6" href="/admin/system-health"><h2 className="text-xl font-semibold">System health</h2><p className="mt-2 text-sm text-slate-600">Review local configuration and database connectivity without exposing secrets.</p></Link></div></section>;
}
