import Link from "next/link";
import { notFound } from "next/navigation";
import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { ownerProject } from "@/lib/payments/core";
import { getUserEntitlements } from "@/lib/billing/entitlements";
import { listPayments, type PaymentFilters } from "@/lib/payments/queries";
import { EXTERNAL_TYPES, formatMoney, METHODS, STATUSES } from "@/lib/payments/validation";
import { PaymentForm, ReceiptItems } from "@/components/payment-form";

export const dynamic = "force-dynamic";
const field = "mt-1 w-full rounded-lg border border-slate-300 bg-white p-2.5";
function Input({ name, label, value, type = "text", required = false }: { name: string; label: string; value?: string | number | null; type?: string; required?: boolean }) { return <label className="block text-sm">{label}<input className={field} name={name} type={type} defaultValue={value ?? undefined} required={required} maxLength={name === "url" ? 2000 : 1000} {...(type === "number" ? { min: 0, max: 10000, step: "0.01" } : {})} /></label>; }
function Select({ name, label, options, value }: { name: string; label: string; options: readonly string[]; value?: string }) { return <label className="block text-sm">{label}<select name={name} defaultValue={value} className={field}>{options.map((option) => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select></label>; }
function Enabled({ enabled = true }: { enabled?: boolean }) { return <label className="flex items-center gap-2 text-sm"><input type="checkbox" name="enabled" defaultChecked={enabled} /> Show on published website</label>; }
export default async function PaymentsPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<PaymentFilters> }) {
  const { id } = await params;
  const owned = await ownerProject(id).catch(() => null); if (!owned) notFound();
  const { project, user } = owned;
  const [entitlements, links, offers, list] = await Promise.all([getUserEntitlements(user.id), prisma.externalPaymentOption.findMany({ where: { projectId: id }, orderBy: { sortOrder: "asc" }, take: 10 }), prisma.paymentItem.findMany({ where: { projectId: id }, orderBy: { createdAt: "asc" }, take: 30 }), listPayments(id, await searchParams)]);
  const paid = entitlements.canAcceptCustomerPayments;
  const settings = project.paymentSettings;
  const status = { NOT_CONNECTED: "Not connected", ONBOARDING: "Setup incomplete", PENDING: "Pending verification", ACTIVE: "Ready to accept payments", RESTRICTED: "Restricted", DISABLED: "Disabled" }[settings?.stripeConnectStatus ?? "NOT_CONNECTED"];
  const total = list.summary.reduce((sum, row) => sum + (row._sum.totalAmount ?? 0) - (row._sum.refundedAmount ?? 0), 0);
  const filters = await searchParams;
  const pageLink = (page: number) => `?${new URLSearchParams({ ...Object.fromEntries(Object.entries(filters).filter(([, v]) => typeof v === "string")), page: String(page) })}#transactions`;
  return <section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><Link href={`/dashboard/projects/${id}`} className="text-sm font-semibold underline">Back to project</Link><h1 className="mt-5 text-3xl font-semibold">Payments</h1><p className="mt-2 text-slate-600">{project.businessName} · USD</p>
    <nav className="my-6 flex flex-wrap gap-4 text-sm font-semibold">{["external-links", "stripe", "offers", "record-payment", "transactions"].map((tab) => <a key={tab} href={`#${tab}`} className="capitalize underline">{tab.replaceAll("-", " ")}</a>)}</nav>
    {!paid && <p className="my-6 rounded-xl bg-amber-50 p-4">External payment links are included on Free. <Link href="/account/billing" className="underline">Choose Starter or Business</Link> for card payments and new manual records. Existing receipts remain available.</p>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Total recorded revenue", formatMoney(total)], ["Paid transactions (including refunded)", String(list.summary.reduce((sum, row) => sum + row._count._all, 0))], ["Stripe transactions", String(list.summary.find((r) => r.paymentSource === "STRIPE")?._count._all ?? 0)], ["Manually recorded", String(list.summary.find((r) => r.paymentSource === "MANUAL_EXTERNAL")?._count._all ?? 0)]].map(([label, value]) => <div key={label} className="rounded-xl border p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><p className="mt-3 text-xs text-slate-500">Based on payments recorded in LaunchSite. Revenue excludes recorded refunds and voided records. This is not audited accounting.</p>
    <section id="external-links" className="mt-10 rounded-2xl border p-6"><h2 className="text-2xl font-semibold">External payment links</h2><p className="my-4 text-sm text-slate-600">Use a provider-hosted HTTPS payment page. Never enter bank account numbers, routing numbers, card details, or banking passwords.</p>
      {[...links, null].map((link, i) => <details key={link?.id ?? "new"} className="mt-3 rounded-xl border p-4"><summary className="cursor-pointer font-semibold">{link ? `${link.label}${link.enabled ? "" : " (hidden)"}` : "Add payment link"}</summary><div className="mt-4"><PaymentForm projectId={id} operation="link"><input type="hidden" name="id" value={link?.id ?? ""} /><Select name="type" label="Provider" options={EXTERNAL_TYPES} value={link?.type} /><Input name="label" label="Button label" value={link?.label} required /><Input name="url" label="Secure payment URL" value={link?.url} type="url" required /><Input name="instructions" label="Optional instructions" value={link?.instructions} /><Input name="sortOrder" label="Display order (0–100)" value={link?.sortOrder ?? i} type="number" /><Enabled enabled={link?.enabled} /></PaymentForm></div></details>)}
    </section>
    <section id="stripe" className="mt-6 rounded-2xl border p-6"><h2 className="text-2xl font-semibold">Stripe card payments</h2><p className="mt-3 font-semibold">{status}</p>{settings?.stripeConnectAccountId && !settings.stripePayoutsEnabled && <p className="mt-2 text-sm text-amber-800">Payouts unavailable. Complete any outstanding requirements in Stripe.</p>}<p className="my-4 text-sm text-slate-600">Stripe handles payment details and identity verification. Customer payments go to your connected business account. Available payment methods depend on Stripe and your account.</p><div className="flex flex-wrap gap-4">{paid && <PaymentForm projectId={id} operation="connect" button={settings?.stripeConnectAccountId ? "Continue Stripe setup" : "Connect Stripe"} />}{settings?.stripeConnectAccountId && <PaymentForm projectId={id} operation="refresh" button="Refresh status" />}</div></section>
    <section id="offers" className="mt-6 rounded-2xl border p-6"><h2 className="text-2xl font-semibold">Payment offers</h2><p className="my-3 text-sm text-slate-600">Create a fixed price, deposit, or customer-entered amount. Offers appear when Stripe is ready and your plan includes card payments.</p>{paid && [...offers, null].map((offer) => <details key={offer?.id ?? "new"} className="mt-3 rounded-xl border p-4"><summary className="cursor-pointer font-semibold">{offer ? `${offer.name}${offer.enabled ? "" : " (hidden)"}` : "Add payment offer"}</summary><div className="mt-4"><PaymentForm projectId={id} operation="item"><input name="id" type="hidden" value={offer?.id ?? ""} /><Input name="name" label="Offer name" value={offer?.name} required /><Input name="description" label="Description" value={offer?.description} /><Select name="type" label="Offer type" options={["FIXED", "DEPOSIT", "CUSTOM_AMOUNT"]} value={offer?.type} /><Input name="amount" label="Fixed price or deposit (USD; ignored for custom amount)" value={offer ? (offer.amount / 100).toFixed(2) : ""} type="number" /><div className="grid gap-4 sm:grid-cols-2"><Input name="minAmount" label="Custom minimum (USD)" value={offer ? (offer.minAmount / 100).toFixed(2) : "0.50"} type="number" /><Input name="maxAmount" label="Custom maximum (USD)" value={offer ? (offer.maxAmount / 100).toFixed(2) : "10000"} type="number" /></div><Enabled enabled={offer?.enabled} /></PaymentForm></div></details>)}</section>
    <section id="record-payment" className="mt-6 rounded-2xl border p-6"><h2 className="text-2xl font-semibold">Record a payment</h2><p className="my-3 text-sm text-slate-600">For money you have already received outside Stripe. Recorded manually by your business; LaunchSite does not independently verify these payments.</p>{paid && <details><summary className="cursor-pointer font-semibold underline">Add payment record</summary><div className="mt-5"><PaymentForm projectId={id} operation="manual" button="Record payment and create receipt"><input type="hidden" name="requestId" value={randomUUID()} /><div className="grid gap-4 sm:grid-cols-2"><Input name="customerName" label="Customer name" required /><Input name="customerEmail" label="Customer email (optional)" type="email" /><Input name="customerPhone" label="Phone (optional)" /><Input name="paidAt" label="Payment date" type="date" value={new Date().toISOString().slice(0, 10)} required /></div><ReceiptItems /><div className="grid gap-4 sm:grid-cols-2"><Input name="taxAmount" label="Tax amount (USD; optional)" type="number" value="0" /><Input name="discountAmount" label="Discount (USD; optional)" type="number" value="0" /></div><Select name="paymentMethod" label="Payment method" options={METHODS} /><Input name="externalReference" label="External reference (optional)" /><Input name="note" label="Note printed on receipt (optional)" /></PaymentForm></div></details>}</section>
    <section id="transactions" className="mt-10"><h2 className="text-2xl font-semibold">Transactions and receipts</h2><form className="my-5 grid items-end gap-3 sm:grid-cols-3"><Input name="q" label="Search customer, email, receipt, reference" value={filters.q} /><Select name="method" label="Method" options={["", "STRIPE", ...METHODS]} value={filters.method} /><Select name="status" label="Status" options={["", ...STATUSES]} value={filters.status} /><Input name="from" label="Created from" type="date" value={filters.from} /><Input name="to" label="Created through" type="date" value={filters.to} /><button className="rounded-lg border p-2.5 font-semibold">Filter transactions</button></form><div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr>{["Date", "Receipt", "Customer", "Amount", "Method", "Status", "Source"].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody>{list.items.map((payment) => <tr key={payment.id} className="border-t"><td className="p-3 whitespace-nowrap">{payment.createdAt.toISOString().slice(0, 10)}</td><td className="p-3"><Link className="underline" href={`/dashboard/projects/${id}/payments/${payment.id}`}>{payment.receiptNumber ?? "View payment"}</Link></td><td className="p-3">{payment.customerName}</td><td className="p-3">{formatMoney(payment.totalAmount)}</td><td className="p-3">{payment.paymentMethod.replaceAll("_", " ")}</td><td className="p-3">{payment.paymentStatus.replaceAll("_", " ")}</td><td className="p-3">{payment.paymentSource === "STRIPE" ? "Stripe" : "Recorded manually"}</td></tr>)}</tbody></table></div>{!list.items.length && <p className="mt-4 text-slate-600">No payments match these filters.</p>}<div className="mt-5 flex gap-5 text-sm">{list.page > 1 && <Link href={pageLink(list.page - 1)}>Previous</Link>}<span>Page {list.page} · {list.total} records</span>{list.page < list.pages && <Link href={pageLink(list.page + 1)}>Next</Link>}</div></section>
  </section>;
}
