/* eslint-disable @typescript-eslint/no-require-imports -- test doubles load server modules. */
const assert = require("node:assert/strict");
const { test, beforeEach } = require("node:test");
let events; let published = true; let custom = false; let owner = "user-a";
const prisma = { analyticsEvent: { create: async ({ data, select }) => { const event = { id: `event-${events.length + 1}`, createdAt: new Date(), ...data }; events.push(event); return select ? { id: event.id } : event; }, findMany: async () => events }, domain: { findUnique: async () => custom ? { status: "ACTIVE", project: { id: "project-a", publicSlug: "example-site", isPublished: published } } : null }, websiteProject: { findFirst: async () => published ? { id: "project-a" } : null } };
function stub(name, exports) { const id = require.resolve(name); require.cache[id] = { id, filename: id, loaded: true, exports }; }
stub("../src/lib/prisma.ts", { prisma }); stub("../src/lib/access.ts", { requireProjectAccess: async (id) => { if (id !== "project-a" || owner !== "user-a") throw new Error("Forbidden"); return { id: owner }; } });
const analytics = require("../src/lib/analytics/service.ts");
beforeEach(() => { events = []; published = true; custom = false; owner = "user-a"; process.env.NEXT_PUBLIC_APP_URL = "https://launchsite-two.vercel.app"; });
test("published slug and custom-domain visits map to one project with host types", async () => { await analytics.recordPublicPageView({ slug: "example-site", path: "/", visitorKey: "visitor-1234567890123456", referrer: "https://www.google.com/search?q=x" }, "launchsite-two.vercel.app"); custom = true; await analytics.recordPublicPageView({ slug: "example-site", path: "/about", visitorKey: "visitor-1234567890123456" }, "customer.example.com"); assert.deepEqual(events.map((event) => event.hostType), ["LAUNCHSITE_SLUG", "CUSTOM_DOMAIN"]); assert.equal(events[0].projectId, events[1].projectId); });
test("unpublished and malformed ingestion is rejected", async () => { published = false; await assert.rejects(() => analytics.recordPublicPageView({ slug: "example-site", path: "/" }, "launchsite-two.vercel.app")); published = true; await assert.rejects(() => analytics.recordPublicPageView({ slug: "example-site", path: "/api/private" }, "launchsite-two.vercel.app")); });
test("owner analytics reads are authorized and source normalization is safe", async () => { await analytics.recordPublicPageView({ slug: "example-site", path: "/", visitorKey: "visitor-1234567890123456", referrer: "https://www.google.com/path?email=secret" }, "launchsite-two.vercel.app"); const result = await analytics.getProjectAnalytics("project-a"); assert.equal(result.sevenDays.views, 1); assert.equal(result.sevenDays.visitors, 1); assert.equal(result.sevenDays.sources[0].source, "GOOGLE"); owner = "user-b"; await assert.rejects(() => analytics.getProjectAnalytics("project-a"), /Forbidden/); });
