/* eslint-disable @typescript-eslint/no-require-imports -- test doubles load server modules. */
const assert = require("node:assert/strict");
const { test, beforeEach } = require("node:test");
let entitlement; let subscription; let createdItems; let scheduleCreates; let scheduleUpdates; let selected;
const prisma = { billingAccount: { findUnique: async () => ({ userId: "user-a", stripeCustomerId: "cus-a", stripeSubscriptionId: "sub-a", currentPeriodEnd: new Date(Date.now() + 86400000) }), update: async ({ data }) => { selected = data; return data; } }, websiteProject: { findFirst: async ({ where }) => where.id === "project-a" && where.userId === "user-a" && where.isPublished ? { id: where.id } : null }, featuredBusiness: { upsert: async ({ where }) => { selected = where; return where; } } };
const stripe = { subscriptions: { retrieve: async () => subscription }, subscriptionItems: { create: async (args) => { createdItems.push(args); return { id: "item-featured" }; } }, subscriptionSchedules: { create: async (args) => { scheduleCreates.push(args); return { id: "schedule-1", phases: [{ items: [{ price: "price_base", quantity: 1 }, { price: "price_featured", quantity: 1 }] }] }; }, update: async (id, args) => { scheduleUpdates.push({ id, args }); return {}; } } };
function stub(name, exports) { const id = require.resolve(name); require.cache[id] = { id, filename: id, loaded: true, exports }; }
stub("../src/lib/prisma.ts", { prisma }); stub("../src/lib/access.ts", { requireUser: async () => ({ id: "user-a", role: "USER" }) }); stub("../src/lib/billing/entitlements.ts", { getUserEntitlements: async () => entitlement }); stub("../src/lib/billing/stripe.ts", { getStripe: () => stripe });
process.env.STRIPE_FEATURED_BUSINESS_PRICE_ID = "price_featured";
const addon = require("../src/lib/billing/featured-addon.ts");
beforeEach(() => { entitlement = { canPurchaseFeaturedBusiness: true, hasFeaturedBusinessAddon: true, canSelectFeaturedProject: true }; subscription = { id: "sub-a", customer: "cus-a", status: "active", schedule: null, current_period_end: Math.floor(Date.now() / 1000) + 86400, items: { data: [{ id: "item-base", price: { id: "price_base" }, quantity: 1 }] } }; createdItems = []; scheduleCreates = []; scheduleUpdates = []; selected = null; });
test("free users cannot purchase and paid users add the trusted price to the existing subscription", async () => { entitlement = { canPurchaseFeaturedBusiness: false }; await assert.rejects(() => addon.addFeaturedBusinessAddon(), /active Starter or Business/); entitlement = { canPurchaseFeaturedBusiness: true }; await addon.addFeaturedBusinessAddon(); assert.deepEqual(createdItems[0], { subscription: "sub-a", price: "price_featured", quantity: 1, proration_behavior: "always_invoice" }); });
test("existing add-on is not duplicated and arbitrary browser price IDs are never used", async () => { subscription.items.data.push({ id: "item-featured", price: { id: "price_featured" }, quantity: 1 }); await assert.rejects(() => addon.addFeaturedBusinessAddon(), /already active/); assert.equal(createdItems.length, 0); });
test("selection requires ownership and publication, and cancellation preserves the base subscription", async () => { await addon.selectFeaturedProject("project-a"); assert.equal(selected.projectId, "project-a"); await assert.rejects(() => addon.selectFeaturedProject("project-b"), /published websites/); subscription.items.data.push({ id: "item-featured", price: { id: "price_featured" }, quantity: 1 }); await addon.cancelFeaturedBusinessAddon(); assert.equal(scheduleCreates.length, 1); assert.equal(scheduleUpdates[0].args.phases[1].items.length, 1); assert.equal(scheduleUpdates[0].args.phases[1].items[0].price, "price_base"); });
