export class BillingError extends Error {
  constructor(public readonly code: "BILLING_NOT_CONFIGURED" | "INVALID_PLAN" | "BILLING_UNAVAILABLE" | "BILLING_CUSTOMER_REQUIRED" | "PUBLISH_REQUIRES_PAID_PLAN" | "PUBLISHED_SITE_LIMIT_REACHED" | "FEATURED_ADDON_NOT_ELIGIBLE" | "FEATURED_ADDON_ALREADY_ACTIVE" | "FEATURED_ADDON_REQUIRED" | "FEATURED_ADDON_SCHEDULE_CONFLICT" | "FEATURED_PROJECT_INVALID", message: string) {
    super(message);
    this.name = "BillingError";
  }
}
