/* eslint-disable @next/next/no-img-element -- Featured demo media is external project media. */
import Link from "next/link";
import { listPublicFeaturedBusinesses } from "@/lib/project-repository";

const steps = [["01", "Tell us the essentials", "Share what you do, who you serve, and where you work."], ["02", "Choose a direction", "Pick a polished visual style that feels like your business."], ["03", "Make it yours", "Review your site, adjust the details, and get ready to share it."]];
const checks = ["A clear, confident first impression", "Services that customers can understand", "A simple way for people to get in touch"];

export default async function Home() {
  const featuredBusinesses = (await listPublicFeaturedBusinesses()).slice(0, 3);
  const featured = featuredBusinesses.map((placement) => ({ ...placement.project, slug: placement.project.isPublished ? placement.project.publicSlug ?? placement.project.slug : placement.project.slug, demoTitle: placement.displayTitle ?? placement.project.business.businessName, demoDescription: placement.promotionalDescription ?? placement.project.business.description }));
  return <>{featured.length > 0 && <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><div className="flex items-end justify-between"><div><p className="eyebrow">Featured examples</p><h2 className="mt-4 text-3xl font-semibold">See LaunchSite in action.</h2></div><Link className="text-sm font-semibold" href="/examples">View all examples</Link></div><div className="mt-8 grid gap-5 md:grid-cols-3">{featured.map((project) => <article className="overflow-hidden rounded-2xl border" key={project.id}>{project.workSamples[0]?.mediaUrl && <img alt="" className="aspect-[4/3] w-full object-cover" src={project.workSamples[0].mediaUrl} />}<div className="p-5"><p className="text-xs text-slate-500">{project.business.category} · {project.siteSettings?.layoutFamily} · {project.visualStyle}</p><h3 className="mt-2 font-semibold">{project.demoTitle ?? project.business.businessName}</h3><p className="mt-2 text-sm text-slate-600">{project.demoDescription ?? project.business.description}</p><Link className="mt-4 inline-block text-sm font-semibold" href={`/examples/${project.slug}`}>View Example</Link></div></article>)}</div></section>}
    <section className="relative border-b border-slate-100"><div className="grid-glow absolute inset-0 -z-10 opacity-70" /><div className="mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-17 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pb-28 lg:pt-24">
      <div><p className="eyebrow"><span className="size-2 rounded-full bg-lime-400" />Built for small businesses</p><h1 className="mt-6 max-w-xl text-5xl font-semibold tracking-[-0.065em] text-slate-950 sm:text-6xl lg:text-7xl">Your business deserves a site that feels <span className="text-slate-500">like you.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-600">Describe your business. LaunchSite turns it into a professional website—without the technical headache.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="rounded-full bg-slate-900 px-6 py-3.5 text-center text-sm font-semibold text-white shadow-lg shadow-slate-900/15 transition hover:-translate-y-0.5 hover:bg-slate-700" href="/register">Create my website <span aria-hidden="true">→</span></Link><a className="rounded-full border border-slate-200 bg-white px-6 py-3.5 text-center text-sm font-semibold text-slate-700 transition hover:border-slate-400" href="#how-it-works">See how it works</a></div><p className="mt-5 text-sm text-slate-500">No design skills. No code. Just your business.</p></div>
      <div className="relative mx-auto w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-3 shadow-2xl shadow-slate-300/45"><div className="overflow-hidden rounded-xl border border-slate-100"><div className="flex items-center gap-1.5 border-b border-slate-100 bg-slate-50 px-4 py-3"><span className="size-2 rounded-full bg-rose-300" /><span className="size-2 rounded-full bg-amber-300" /><span className="size-2 rounded-full bg-lime-400" /><span className="ml-3 h-5 flex-1 rounded bg-white" /></div><div className="bg-[#f7f5ef] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-800">Westside Gardens</p><h2 className="mt-5 max-w-xs text-3xl font-semibold tracking-[-0.05em] text-emerald-950">Outdoor spaces made to live in.</h2><p className="mt-3 max-w-sm text-sm leading-6 text-emerald-900/70">Thoughtful landscape design and dependable care for Tulsa homes.</p><button className="mt-6 rounded-full bg-emerald-900 px-4 py-2.5 text-sm font-semibold text-white" type="button">Request an estimate</button><div className="mt-8 grid grid-cols-3 gap-3"><div className="h-20 rounded-lg bg-[#bfd9b4]" /><div className="h-20 rounded-lg bg-[#9fbf95]" /><div className="h-20 rounded-lg bg-[#d7c49a]" /></div></div></div><div className="absolute -bottom-5 -left-5 rounded-xl border border-slate-100 bg-white px-4 py-3 shadow-lg"><p className="text-xs text-slate-500">From your description to a site</p><p className="mt-0.5 text-sm font-semibold text-slate-900">Made simple <span className="text-lime-600">✦</span></p></div></div>
    </div></section>
    <section className="mx-auto max-w-6xl px-5 py-20 sm:px-8" id="how-it-works"><div className="max-w-xl"><p className="eyebrow">A simpler way to get online</p><h2 className="section-title mt-5">Start with what you already know: your business.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{steps.map(([number, title, text]) => <article className="rounded-2xl border border-slate-200 p-6" key={number}><p className="text-sm font-semibold text-lime-700">{number}</p><h3 className="mt-9 text-xl font-semibold tracking-[-0.03em]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>
    <section className="bg-slate-950 py-20 text-white" id="examples"><div className="mx-auto grid max-w-6xl gap-10 px-5 sm:px-8 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow border-slate-700 bg-slate-900 text-slate-300">Made to earn trust</p><h2 className="mt-5 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">A professional presence should not be hard to begin.</h2><p className="mt-5 max-w-lg leading-7 text-slate-300">LaunchSite helps you present the work you do with clarity—so the right customers feel confident reaching out.</p><Link className="mt-8 inline-flex rounded-full bg-lime-300 px-5 py-3 text-sm font-semibold text-slate-950 transition hover:bg-lime-200" href="/register">Start your website</Link></div><div className="rounded-2xl bg-slate-900 p-6 sm:p-8"><p className="text-sm font-medium text-lime-300">A solid first website includes:</p><ul className="mt-6 space-y-5">{checks.map((check) => <li className="flex gap-3 text-slate-200" key={check}><span className="grid size-6 shrink-0 place-items-center rounded-full bg-lime-300 text-xs font-bold text-slate-950">✓</span>{check}</li>)}</ul></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-20 sm:px-8" id="why-launchsite"><div className="rounded-3xl bg-[#eef6e4] px-6 py-12 text-center sm:px-12"><p className="eyebrow">Your next customer is searching</p><h2 className="mx-auto mt-5 max-w-2xl text-3xl font-semibold tracking-[-0.05em] text-slate-950 sm:text-5xl">Give them a reason to choose you.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-slate-600">Bring your business online with a website that feels considered from day one.</p><Link className="mt-8 inline-flex rounded-full bg-slate-900 px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-slate-700" href="/register">Create my website <span className="ml-1">→</span></Link></div></section>
  </>;
}
