"use client";
/* eslint-disable @next/next/no-img-element -- Google profile images are external URLs. */

import Link from "next/link";
import { useState } from "react";
import { changeUserRoleAction } from "@/app/actions/projects";
import { deleteUserAction, resetUserBillingAction } from "@/app/actions/admin-users";

type AdminUser = { id: string; name: string | null; email: string | null; image: string | null; role: "USER" | "ADMIN"; createdAt: Date; _count: { projects: number }; publishedProjectCount: number; billingPlan: "FREE" | "STARTER" | "BUSINESS"; billingStatus: string | null; hasStripeCustomer: boolean; hasStripeSubscription: boolean };

export function AdminUsersTable({ users }: { users: AdminUser[] }) {
  const [message, setMessage] = useState("");
  const changeRole = async (id: string, role: "USER" | "ADMIN") => { const result = await changeUserRoleAction(id, role); setMessage(result.ok ? "User role updated." : result.error); };
  const reset = async (user: AdminUser) => { if (user.role === "ADMIN") return; if (!window.confirm("Reset billing? This keeps the account and all content, and returns only LaunchSite billing to Free. Stripe is not refunded or changed.")) return; const hasSubscription = user.hasStripeSubscription; const confirmation = hasSubscription ? window.prompt(`An existing Stripe subscription is linked. Type ${user.email ?? "the user's email"} to confirm that Stripe remains unchanged and only LaunchSite billing is reset.`) ?? "" : undefined; const result = await resetUserBillingAction(user.id, confirmation, hasSubscription); setMessage(result.ok ? "Billing reset to Free. Stripe was not changed." : result.error); };
  const remove = async (user: AdminUser) => { if (user.role === "ADMIN" || !user.email) return; if (!window.confirm("Delete this user permanently? Their account and customer-owned sites will be deleted. This cannot be undone.")) return; const confirmation = window.prompt(`Type ${user.email} to permanently delete this user and their customer-owned data.`); if (confirmation === null) return; const result = await deleteUserAction(user.id, confirmation); setMessage(result.ok ? "User and customer-owned data deleted." : result.error); };
  return <><p className="mb-4 text-sm text-slate-600">Reset billing keeps the account and content, returning local billing to Free. Delete user permanently removes the account and customer-owned site data; shared/demo sites are preserved.</p><div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">User</th><th className="p-4">Role</th><th className="p-4">Sites</th><th className="p-4">Published</th><th className="p-4">Billing</th><th className="p-4">Stripe links</th><th className="p-4">Joined</th><th className="p-4">Actions</th></tr></thead><tbody>{users.map((user) => <tr className="border-t" key={user.id}><td className="p-4"><div className="flex items-center gap-3">{user.image ? <img alt="" className="size-8 rounded-full" src={user.image} /> : <span className="grid size-8 place-items-center rounded-full bg-slate-100 text-xs">{user.name?.[0] ?? "?"}</span>}<div><p className="font-semibold">{user.name ?? "Unnamed user"}</p><p className="text-slate-500">{user.email ?? "No email"}</p></div></div></td><td className="p-4">{user.role}</td><td className="p-4"><Link className="font-semibold underline" href={`/admin/users/${user.id}`}>{user._count.projects}</Link></td><td className="p-4">{user.publishedProjectCount}</td><td className="p-4"><span className="font-semibold">{user.billingPlan}</span><br /><span className="text-slate-500">{user.billingStatus ?? "No subscription"}</span></td><td className="p-4">Customer: {user.hasStripeCustomer ? "yes" : "no"}<br />Subscription: {user.hasStripeSubscription ? "yes" : "no"}</td><td className="p-4">{new Date(user.createdAt).toLocaleDateString()}</td><td className="p-4"><div className="flex flex-col items-start gap-2">{user.role === "USER" && <><button className="font-semibold text-slate-900" onClick={() => reset(user)} type="button">Reset billing</button><button className="font-semibold text-rose-700" onClick={() => remove(user)} type="button">Delete user</button></>}{user.role === "ADMIN" && <button className="font-semibold text-slate-900" onClick={() => changeRole(user.id, "USER")} type="button">Make user</button>}</div></td></tr>)}</tbody></table></div>{message && <p className="mt-4 text-sm" role="status">{message}</p>}</>;
}
