"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { saveProjectAction } from "@/app/actions/projects";
import { TestimonialEditor, WorkSampleEditor } from "@/components/proof-source-editors";
import { brandTones, callToActions, initialBusinessProfile, visualStyles, type BusinessProfile, type BusinessService, type PersistedWebsiteProject, type VisualStyle } from "@/lib/website-types";

const steps = ["Basics", "Services", "About", "Customers", "Voice", "Contact", "Style", "Work", "Reviews", "Review"];
const input = "mt-2 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 text-slate-950 outline-none focus:border-slate-900";
function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-slate-800"><span>{label}</span>{hint && <span className="mt-1 block font-normal text-slate-500">{hint}</span>}{children}</label>; }

export function CreateWizard({ initialProject, initialStep }: { initialProject?: PersistedWebsiteProject; initialStep?: number }) {
  const router = useRouter(); const [step, setStep] = useState(initialStep ?? (initialProject ? 9 : 0)); const [business, setBusiness] = useState<BusinessProfile>(initialProject?.business ?? initialBusinessProfile); const [visualStyle, setVisualStyle] = useState<VisualStyle>(initialProject?.visualStyle ?? "Modern"); const [workSamples, setWorkSamples] = useState(initialProject?.workSamples ?? []); const [testimonials, setTestimonials] = useState(initialProject?.testimonials ?? []); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const update = <K extends keyof BusinessProfile>(key: K, value: BusinessProfile[K]) => setBusiness((current) => ({ ...current, [key]: value }));
  const service = (index: number, key: keyof BusinessService, value: string) => update("services", business.services.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const move = (index: number, offset: -1 | 1) => { const target = index + offset; if (target < 0 || target >= business.services.length) return; const next = [...business.services]; [next[index], next[target]] = [next[target], next[index]]; update("services", next); };
  const validationError = () => step === 0 && (!business.businessName.trim() || !business.category.trim() || business.description.trim().length < 20 || !business.serviceArea.trim()) ? "Please complete the required business basics." : step === 1 && (!business.services.length || business.services.some((item) => !item.name.trim())) ? "Add at least one named service." : step === 5 && (!business.phone.trim() || !/^\S+@\S+\.\S+$/.test(business.email)) ? "Please provide a phone number and valid email address." : null;
  const next = () => { const message = validationError(); if (message) { setError(message); return; } setError(null); setStep((current) => Math.min(current + 1, 9)); };
  const save = async () => { setSaving(true); setError(null); const result = await saveProjectAction({ business, visualStyle, workSamples, testimonials }, initialProject?.id); setSaving(false); if (!result.ok) { setError(result.error); return; } router.push(`/dashboard/projects/${result.id}`); router.refresh(); };
  return <section className="bg-slate-50 py-10 sm:py-14"><div className="mx-auto max-w-4xl px-5 sm:px-8"><p className="eyebrow">{initialProject ? "Edit business facts" : "Create your website"}</p><h1 className="mt-4 text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">Tell us about the real work behind your business.</h1><p className="mt-3 max-w-2xl leading-7 text-slate-600">Short answers are fine. These facts guide your website—we’ll handle the marketing language later.</p><ol className="mt-8 grid grid-cols-5 gap-2 sm:grid-cols-10">{steps.map((label, index) => <li key={label}><span className={`grid size-7 place-items-center rounded-full text-xs font-bold ${index <= step ? "bg-slate-900 text-white" : "bg-slate-200 text-slate-500"}`}>{index + 1}</span><span className="mt-1 hidden text-xs text-slate-500 sm:block">{label}</span></li>)}</ol><div className="mt-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
    {step === 0 && <div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><h2 className="text-2xl font-semibold">Business basics</h2><p className="mt-2 text-slate-600">Start with the essential facts customers should know.</p></div><Field label="Business name *"><input className={input} onChange={(e) => update("businessName", e.target.value)} value={business.businessName} /></Field><Field label="What kind of business is this? *"><input className={input} onChange={(e) => update("category", e.target.value)} value={business.category} /></Field><div className="sm:col-span-2"><Field label="Brief business overview *" hint="In a sentence or two, explain what you do."><textarea className={`${input} min-h-28`} onChange={(e) => update("description", e.target.value)} value={business.description} /></Field></div><div className="sm:col-span-2"><Field label="Where do you work? *"><input className={input} onChange={(e) => update("serviceArea", e.target.value)} value={business.serviceArea} /></Field></div></div>}
    {step === 1 && <div><h2 className="text-2xl font-semibold">Your services</h2><p className="mt-2 text-slate-600">Add factual details. You do not need to write marketing copy.</p><div className="mt-6 space-y-4">{business.services.map((item, index) => <div className="rounded-xl border border-slate-200 p-4" key={item.id}><div className="flex justify-between"><p className="font-semibold">Service {index + 1}</p><div className="flex gap-2"><button disabled={index === 0} onClick={() => move(index, -1)} type="button">↑</button><button disabled={index === business.services.length - 1} onClick={() => move(index, 1)} type="button">↓</button><button className="text-rose-700" onClick={() => update("services", business.services.filter((_, i) => i !== index))} type="button">Remove</button></div></div><div className="mt-4 grid gap-4"><Field label="Service name *"><input className={input} onChange={(e) => service(index, "name", e.target.value)} value={item.name} /></Field><Field label="What does it include?" hint="Plain factual description."><textarea className={`${input} min-h-20`} onChange={(e) => service(index, "description", e.target.value)} value={item.description} /></Field><Field label="Who or what is it for?" hint="Optional use cases or needs."><input className={input} onChange={(e) => service(index, "notes", e.target.value)} value={item.notes} /></Field></div></div>)}</div><button className="mt-5 rounded-full border border-slate-300 px-4 py-2.5 text-sm font-semibold" onClick={() => update("services", [...business.services, { id: crypto.randomUUID(), name: "", description: "", notes: "" }])} type="button">+ Add a service</button></div>}
    {step === 2 && <div className="grid gap-5"><h2 className="text-2xl font-semibold">About your business</h2><Field label="How did your business get started?" hint="Optional background or history."><textarea className={`${input} min-h-28`} onChange={(e) => update("businessStory", e.target.value)} value={business.businessStory} /></Field><Field label="Years in business" hint="Optional."><input className={input} onChange={(e) => update("yearsInBusiness", e.target.value)} type="number" value={business.yearsInBusiness} /></Field><Field label="Anything else we should know?" hint="Optional factual notes."><textarea className={`${input} min-h-24`} onChange={(e) => update("factualNotes", e.target.value)} value={business.factualNotes} /></Field></div>}
    {step === 3 && <div className="grid gap-5"><h2 className="text-2xl font-semibold">Your customers</h2><Field label="Who do you usually help?"><textarea className={`${input} min-h-24`} onChange={(e) => update("targetAudience", e.target.value)} value={business.targetAudience} /></Field><Field label="What makes your business different?"><textarea className={`${input} min-h-24`} onChange={(e) => update("differentiators", e.target.value)} value={business.differentiators} /></Field><Field label="What matters most to customers?"><textarea className={`${input} min-h-24`} onChange={(e) => update("customerPriorities", e.target.value)} value={business.customerPriorities} /></Field></div>}
    {step === 4 && <div className="grid gap-3"><h2 className="mb-3 text-2xl font-semibold">Brand voice</h2>{brandTones.map((tone) => <button className={`rounded-xl border p-4 text-left ${business.tone === tone ? "border-slate-950 bg-slate-950 text-white" : "border-slate-200"}`} key={tone} onClick={() => update("tone", tone)} type="button">{tone}</button>)}</div>}
    {step === 5 && <div className="grid gap-5"><h2 className="text-2xl font-semibold">Make it easy to reach you</h2><Field label="Phone number *"><input className={input} onChange={(e) => update("phone", e.target.value)} value={business.phone} /></Field><Field label="Email address *"><input className={input} onChange={(e) => update("email", e.target.value)} type="email" value={business.email} /></Field><Field label="What should visitors do first?"><select className={input} onChange={(e) => update("callToAction", e.target.value as BusinessProfile["callToAction"])} value={business.callToAction}>{callToActions.map((action) => <option key={action}>{action}</option>)}</select></Field><Field label="A secondary action (optional)"><input className={input} onChange={(e) => update("secondaryCallToAction", e.target.value)} value={business.secondaryCallToAction} /></Field></div>}
    {step === 6 && <div><h2 className="text-2xl font-semibold">Choose a visual direction</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{visualStyles.map((style) => <button className={`rounded-xl border p-5 text-left ${visualStyle === style ? "border-slate-950 bg-slate-950 text-white" : "border-slate-200"}`} key={style} onClick={() => setVisualStyle(style)} type="button"><span className="text-lg font-semibold">{style}</span></button>)}</div></div>}
    {step === 7 && <WorkSampleEditor onChange={setWorkSamples} projectId={initialProject?.id} samples={workSamples} />}
    {step === 8 && <TestimonialEditor onChange={setTestimonials} testimonials={testimonials} />}
    {step === 9 && <div><h2 className="text-2xl font-semibold">Review your business facts</h2><p className="mt-2 text-slate-600">Go back to correct anything before saving.</p><dl className="mt-7 grid gap-5 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Business</dt><dd className="font-semibold">{business.businessName} · {business.category}</dd></div><div><dt className="text-sm text-slate-500">Service area</dt><dd className="font-semibold">{business.serviceArea}</dd></div><div className="sm:col-span-2"><dt className="text-sm text-slate-500">Services</dt><dd className="font-semibold">{business.services.map((item) => item.name || "Unnamed service").join(", ") || "None added"}</dd></div><div><dt className="text-sm text-slate-500">Work samples</dt><dd className="font-semibold">{workSamples.length || "None"}</dd></div><div><dt className="text-sm text-slate-500">Testimonials</dt><dd className="font-semibold">{testimonials.length || "None"}</dd></div></dl></div>}
    {error && <p className="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-medium text-rose-700">{error}</p>}<div className="mt-8 flex justify-between"><button className="rounded-full px-4 py-2.5 text-sm font-semibold disabled:opacity-30" disabled={step === 0} onClick={() => { setError(null); setStep((current) => current - 1); }} type="button">← Back</button>{step < 9 ? <button className="rounded-full bg-slate-900 px-5 py-3 text-sm font-semibold text-white" onClick={next} type="button">Continue →</button> : <button className="rounded-full bg-slate-900 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60" disabled={saving} onClick={save} type="button">{saving ? "Saving…" : initialProject ? "Save changes" : "Save project"}</button>}</div>
  </div></div></section>;
}
