"use client";

import { useState } from "react";
import type { Testimonial, WorkSample } from "@/lib/website-types";

const input = "mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm text-slate-950";
const newId = () => crypto.randomUUID();
function Move({ index, length, move, remove }: { index: number; length: number; move: (offset: -1 | 1) => void; remove: () => void }) { return <div className="flex gap-2 text-sm"><button disabled={index === 0} onClick={() => move(-1)} type="button">Up</button><button disabled={index === length - 1} onClick={() => move(1)} type="button">Down</button><button className="text-rose-700" onClick={remove} type="button">Remove</button></div>; }

function Upload({ mediaType, projectId, done }: { mediaType: WorkSample["mediaType"]; projectId?: string; done: (data: Partial<WorkSample>) => void }) {
  const [state, setState] = useState<"ready" | "uploading" | "success" | "error">("ready"); const [message, setMessage] = useState("");
  const upload = async (file?: File) => { if (!file) return; const image = mediaType === "IMAGE"; const max = image ? 10 * 1024 * 1024 : 100 * 1024 * 1024; if (!projectId) { setState("error"); setMessage("Save this project first, then upload media."); return; } if (!file.type.startsWith(image ? "image/" : "video/") || file.size > max) { setState("error"); setMessage(image ? "Choose an image up to 10 MB." : "Choose a video up to 100 MB."); return; } setState("uploading"); setMessage(""); try { const signedResponse = await fetch(`/api/projects/${projectId}/work-samples/upload-signature`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mediaType }) }); const signed = await signedResponse.json() as { error?: string; cloudName?: string; apiKey?: string; timestamp?: number; folder?: string; signature?: string; resourceType?: string; allowedFormats?: string; maxFileSize?: number }; if (!signedResponse.ok || !signed.cloudName || !signed.apiKey || !signed.timestamp || !signed.folder || !signed.signature || !signed.resourceType) throw new Error(signed.error ?? "Could not prepare upload."); const form = new FormData(); form.append("file", file); form.append("api_key", signed.apiKey); form.append("timestamp", String(signed.timestamp)); form.append("folder", signed.folder); form.append("allowed_formats", signed.allowedFormats ?? (mediaType === "IMAGE" ? "jpg,png,webp" : "mp4,mov,webm")); form.append("max_file_size", String(signed.maxFileSize ?? max)); form.append("signature", signed.signature); const response = await fetch(`https://api.cloudinary.com/v1_1/${signed.cloudName}/${signed.resourceType}/upload`, { method: "POST", body: form }); const asset = await response.json() as { error?: { message?: string }; secure_url?: string; public_id?: string; width?: number; height?: number; duration?: number; format?: string; bytes?: number }; if (!response.ok || !asset.secure_url || !asset.public_id) throw new Error(asset.error?.message ?? "Upload failed."); done({ mediaUrl: asset.secure_url, cloudinaryPublicId: asset.public_id, width: asset.width, height: asset.height, duration: asset.duration, format: asset.format, bytes: asset.bytes }); setState("success"); setMessage("Upload complete. Save changes to keep it on this project."); } catch (error) { setState("error"); setMessage(error instanceof Error ? error.message : "Upload failed."); } };
  const accept = mediaType === "IMAGE" ? "image/*" : "video/*";
  return <div className="sm:col-span-2"><p className="text-sm font-semibold">Add media</p><div className="mt-2 flex flex-wrap gap-3"><label className="cursor-pointer rounded-full border border-slate-300 px-3 py-2 text-sm font-semibold"><input accept={accept} className="sr-only" disabled={state === "uploading"} onChange={(e) => upload(e.target.files?.[0])} type="file" />{mediaType === "IMAGE" ? "Upload photo" : "Upload video"}</label><label className="cursor-pointer rounded-full border border-slate-300 px-3 py-2 text-sm font-semibold"><input accept={accept} capture="environment" className="sr-only" disabled={state === "uploading"} onChange={(e) => upload(e.target.files?.[0])} type="file" />{mediaType === "IMAGE" ? "Take photo" : "Capture video"}</label></div>{state !== "ready" && <p className={state === "error" ? "mt-2 text-sm text-rose-700" : "mt-2 text-sm text-lime-700"}>{state === "uploading" ? "Uploading..." : message}</p>}<p className="mt-2 text-xs text-slate-500">Or paste a URL below. {mediaType === "IMAGE" ? "Images up to 10 MB." : "Videos up to 100 MB."}</p></div>;
}

export function WorkSampleEditor({ samples, onChange, projectId, errors = {} }: { samples: WorkSample[]; onChange: (samples: WorkSample[]) => void; projectId?: string; errors?: Record<string, string> }) {
  const update = (index: number, key: keyof WorkSample, value: string) => onChange(samples.map((sample, i) => i === index ? { ...sample, [key]: value } : sample));
  const setExternalUrl = (index: number, mediaUrl: string) => onChange(samples.map((sample, i) => i === index ? { ...sample, mediaUrl, cloudinaryPublicId: undefined, width: undefined, height: undefined, duration: undefined, format: undefined, bytes: undefined } : sample));
  const move = (index: number, offset: -1 | 1) => { const target = index + offset; if (target < 0 || target >= samples.length) return; const next = [...samples]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  return <div><h2 className="text-2xl font-semibold">Show examples of your work</h2><p className="mt-2 text-slate-600">Optional. Upload from your device, take a photo where supported, or paste a media URL.</p><div className="mt-6 space-y-4">{samples.map((sample, index) => <div className={`rounded-xl border p-4 ${errors[sample.id] ? "border-rose-300 bg-rose-50/40" : "border-slate-200"}`} key={sample.id}><div className="flex justify-between"><p className="font-semibold">Work sample {index + 1}</p><Move index={index} length={samples.length} move={(offset) => move(index, offset)} remove={() => onChange(samples.filter((_, i) => i !== index))} /></div>{errors[sample.id] && <p className="mt-3 text-sm font-medium text-rose-700">{errors[sample.id]}</p>}<div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Media type<select className={input} onChange={(e) => update(index, "mediaType", e.target.value)} value={sample.mediaType}><option value="IMAGE">Image</option><option value="VIDEO">Video</option></select></label><label>Media URL *<input className={input} onChange={(e) => setExternalUrl(index, e.target.value)} placeholder="https://..." value={sample.mediaUrl} /></label><Upload done={(data) => onChange(samples.map((item, i) => i === index ? { ...item, ...data } : item))} mediaType={sample.mediaType} projectId={projectId} /><label>Title *<input className={input} onChange={(e) => update(index, "title", e.target.value)} value={sample.title} /></label><label>Related service (optional)<input className={input} onChange={(e) => update(index, "serviceCategory", e.target.value)} value={sample.serviceCategory} /></label><label className="sm:col-span-2">What happened? (optional)<textarea className={`${input} min-h-20`} onChange={(e) => update(index, "description", e.target.value)} value={sample.description} /></label><label className="sm:col-span-2">Location or project note (optional)<input className={input} onChange={(e) => update(index, "locationNote", e.target.value)} value={sample.locationNote} /></label></div></div>)}</div><button className="mt-5 rounded-full border border-slate-300 px-4 py-2.5 text-sm font-semibold" onClick={() => onChange([...samples, { id: newId(), mediaType: "IMAGE", mediaUrl: "", title: "", description: "", serviceCategory: "", locationNote: "" }])} type="button">+ Add work sample</button></div>;
}

export function TestimonialEditor({ testimonials, onChange }: { testimonials: Testimonial[]; onChange: (testimonials: Testimonial[]) => void }) {
  const update = (index: number, key: keyof Testimonial, value: string) => onChange(testimonials.map((item, i) => i === index ? { ...item, [key]: value } : item)); const move = (index: number, offset: -1 | 1) => { const target = index + offset; if (target < 0 || target >= testimonials.length) return; const next = [...testimonials]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  return <div><h2 className="text-2xl font-semibold">Share customer feedback</h2><p className="mt-2 text-slate-600">Optional. Only add real feedback supplied by your business.</p><div className="mt-6 space-y-4">{testimonials.map((item, index) => <div className="rounded-xl border border-slate-200 p-4" key={item.id}><div className="flex justify-between"><p className="font-semibold">Testimonial {index + 1}</p><Move index={index} length={testimonials.length} move={(offset) => move(index, offset)} remove={() => onChange(testimonials.filter((_, i) => i !== index))} /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Customer name or initials *<input className={input} onChange={(e) => update(index, "customerName", e.target.value)} value={item.customerName} /></label><label>Service type (optional)<input className={input} onChange={(e) => update(index, "serviceType", e.target.value)} value={item.serviceType} /></label><label className="sm:col-span-2">Their testimonial *<textarea className={`${input} min-h-24`} onChange={(e) => update(index, "testimonialText", e.target.value)} value={item.testimonialText} /></label><label>Customer city or location (optional)<input className={input} onChange={(e) => update(index, "locationNote", e.target.value)} value={item.locationNote} /></label><label>Supplied rating (optional, 1-5)<input className={input} max="5" min="1" onChange={(e) => update(index, "rating", e.target.value)} type="number" value={item.rating} /></label></div></div>)}</div><button className="mt-5 rounded-full border border-slate-300 px-4 py-2.5 text-sm font-semibold" onClick={() => onChange([...testimonials, { id: newId(), customerName: "", testimonialText: "", serviceType: "", locationNote: "", rating: "" }])} type="button">+ Add testimonial</button></div>;
}
