"use client";

import type { Testimonial, WorkSample } from "@/lib/website-types";

const input = "mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm text-slate-950";
const newId = () => crypto.randomUUID();

function MoveButtons({ index, length, onMove, onRemove }: { index: number; length: number; onMove: (offset: -1 | 1) => void; onRemove: () => void }) { return <div className="flex gap-2 text-sm"><button disabled={index === 0} onClick={() => onMove(-1)} type="button">↑</button><button disabled={index === length - 1} onClick={() => onMove(1)} type="button">↓</button><button className="text-rose-700" onClick={onRemove} type="button">Remove</button></div>; }

export function WorkSampleEditor({ samples, onChange }: { samples: WorkSample[]; onChange: (samples: WorkSample[]) => void }) {
  const update = (index: number, key: keyof WorkSample, value: string) => onChange(samples.map((sample, sampleIndex) => sampleIndex === index ? { ...sample, [key]: value } : sample));
  const move = (index: number, offset: -1 | 1) => { const target = index + offset; if (target < 0 || target >= samples.length) return; const next = [...samples]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  return <div><h2 className="text-2xl font-semibold">Show examples of your work</h2><p className="mt-2 text-slate-600">Optional. Add an image or direct video URL for a real project. Files are not uploaded or stored here.</p><div className="mt-6 space-y-4">{samples.map((sample, index) => <div className="rounded-xl border border-slate-200 p-4" key={sample.id}><div className="flex justify-between"><p className="font-semibold">Work sample {index + 1}</p><MoveButtons index={index} length={samples.length} onMove={(offset) => move(index, offset)} onRemove={() => onChange(samples.filter((_, itemIndex) => itemIndex !== index))} /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Media type<select className={input} onChange={(event) => update(index, "mediaType", event.target.value)} value={sample.mediaType}><option value="IMAGE">Image</option><option value="VIDEO">Video</option></select></label><label>Image or video URL *<input className={input} onChange={(event) => update(index, "mediaUrl", event.target.value)} placeholder="https://…" value={sample.mediaUrl} /></label><label>Title *<input className={input} onChange={(event) => update(index, "title", event.target.value)} value={sample.title} /></label><label>Related service (optional)<input className={input} onChange={(event) => update(index, "serviceCategory", event.target.value)} value={sample.serviceCategory} /></label><label className="sm:col-span-2">What happened? (optional)<textarea className={`${input} min-h-20`} onChange={(event) => update(index, "description", event.target.value)} value={sample.description} /></label><label className="sm:col-span-2">Location or project note (optional)<input className={input} onChange={(event) => update(index, "locationNote", event.target.value)} value={sample.locationNote} /></label></div></div>)}</div><button className="mt-5 rounded-full border border-slate-300 px-4 py-2.5 text-sm font-semibold" onClick={() => onChange([...samples, { id: newId(), mediaType: "IMAGE", mediaUrl: "", title: "", description: "", serviceCategory: "", locationNote: "" }])} type="button">+ Add work sample</button></div>;
}

export function TestimonialEditor({ testimonials, onChange }: { testimonials: Testimonial[]; onChange: (testimonials: Testimonial[]) => void }) {
  const update = (index: number, key: keyof Testimonial, value: string) => onChange(testimonials.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const move = (index: number, offset: -1 | 1) => { const target = index + offset; if (target < 0 || target >= testimonials.length) return; const next = [...testimonials]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  return <div><h2 className="text-2xl font-semibold">Share customer feedback</h2><p className="mt-2 text-slate-600">Optional. Only add real feedback supplied by your business. We never invent testimonials or ratings.</p><div className="mt-6 space-y-4">{testimonials.map((testimonial, index) => <div className="rounded-xl border border-slate-200 p-4" key={testimonial.id}><div className="flex justify-between"><p className="font-semibold">Testimonial {index + 1}</p><MoveButtons index={index} length={testimonials.length} onMove={(offset) => move(index, offset)} onRemove={() => onChange(testimonials.filter((_, itemIndex) => itemIndex !== index))} /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Customer name or initials *<input className={input} onChange={(event) => update(index, "customerName", event.target.value)} value={testimonial.customerName} /></label><label>Service type (optional)<input className={input} onChange={(event) => update(index, "serviceType", event.target.value)} value={testimonial.serviceType} /></label><label className="sm:col-span-2">Their testimonial *<textarea className={`${input} min-h-24`} onChange={(event) => update(index, "testimonialText", event.target.value)} value={testimonial.testimonialText} /></label><label>Customer city or location (optional)<input className={input} onChange={(event) => update(index, "locationNote", event.target.value)} value={testimonial.locationNote} /></label><label>Supplied rating (optional, 1–5)<input className={input} max="5" min="1" onChange={(event) => update(index, "rating", event.target.value)} type="number" value={testimonial.rating} /></label></div></div>)}</div><button className="mt-5 rounded-full border border-slate-300 px-4 py-2.5 text-sm font-semibold" onClick={() => onChange([...testimonials, { id: newId(), customerName: "", testimonialText: "", serviceType: "", locationNote: "", rating: "" }])} type="button">+ Add testimonial</button></div>;
}
