import type { WebsiteProject } from "@/lib/website-types";

const styles = {
  Modern: { accent: "bg-cyan-400", ink: "text-slate-950", surface: "bg-slate-950", card: "bg-cyan-50", button: "bg-cyan-400 text-slate-950" },
  Bold: { accent: "bg-orange-500", ink: "text-slate-950", surface: "bg-orange-500", card: "bg-orange-50", button: "bg-orange-500 text-white" },
  Professional: { accent: "bg-blue-700", ink: "text-slate-950", surface: "bg-blue-950", card: "bg-blue-50", button: "bg-blue-700 text-white" },
  Friendly: { accent: "bg-lime-400", ink: "text-slate-950", surface: "bg-emerald-950", card: "bg-lime-50", button: "bg-lime-400 text-slate-950" },
  Minimal: { accent: "bg-stone-800", ink: "text-stone-900", surface: "bg-stone-900", card: "bg-stone-100", button: "bg-stone-900 text-white" },
} as const;

export function SiteRenderer({ project }: { project: WebsiteProject }) {
  const { business } = project;
  const aiContent = project.generatedContent;
  const content = aiContent ? { tagline: aiContent.tagline, heroHeading: aiContent.hero.headline, heroDescription: aiContent.hero.supportingText, services: aiContent.services, about: aiContent.about.body, benefits: aiContent.benefits, contactPrompt: aiContent.contact.body } : project.content;
  const theme = styles[project.visualStyle];
  const emailHref = `mailto:${encodeURIComponent(business.email)}`;
  const phoneHref = `tel:${business.phone.replace(/[^+\d]/g, "")}`;

  return <article className={`overflow-hidden bg-white ${theme.ink}`}>
    <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><p className="text-lg font-bold tracking-[-0.04em]">{business.businessName}</p><a className="hidden text-sm font-medium text-slate-600 sm:block" href="#contact">Contact</a></header>
    <section className={`${theme.card} border-y border-slate-200`}><div className="mx-auto grid max-w-6xl gap-10 px-5 py-18 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-slate-600">{content.tagline}</p><h1 className="mt-5 max-w-2xl text-4xl font-semibold tracking-[-0.06em] sm:text-6xl">{content.heroHeading}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">{content.heroDescription}</p><a className={`mt-8 inline-flex rounded-full px-5 py-3 text-sm font-semibold transition hover:opacity-85 ${theme.button}`} href="#contact">{business.callToAction} <span className="ml-2">→</span></a></div><div className={`${theme.surface} rounded-2xl p-7 text-white shadow-xl sm:p-9`}><div className={`size-10 rounded-full ${theme.accent}`} /><p className="mt-12 text-sm font-semibold uppercase tracking-widest text-white/60">Local expertise</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em]">Good work starts with a conversation.</p><p className="mt-4 leading-7 text-white/70">Serving neighbors across {business.serviceArea} with care and confidence.</p></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-18 sm:px-8"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-slate-500">What we do</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em]">Services designed around you.</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{content.services.map((service, index) => <div className="rounded-xl border border-slate-200 p-5" key={service.name}><p className="text-sm font-semibold text-slate-400">0{index + 1}</p><h3 className="mt-7 text-lg font-semibold">{service.name}</h3><p className="mt-2 leading-6 text-slate-600">{service.description}</p></div>)}</div></section>
    <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-18 sm:px-8 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-slate-500">About us</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em]">{aiContent?.about.heading ?? "Built on the details that matter."}</h2></div><p className="text-lg leading-8 text-slate-600">{content.about}</p></div></section>
    <section className="mx-auto max-w-6xl px-5 py-18 sm:px-8"><div className="rounded-2xl bg-slate-950 px-6 py-10 text-white sm:px-10"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-white/60">Why choose us</p><div className="mt-7 grid gap-5 md:grid-cols-3">{content.benefits.map((benefit) => <p className="flex gap-3 leading-6" key={benefit}><span className={`grid size-6 shrink-0 place-items-center rounded-full text-xs ${theme.accent} text-slate-950`}>✓</span>{benefit}</p>)}</div></div></section>
    <section className={`${theme.card}`} id="contact"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-18 sm:px-8 lg:grid-cols-2 lg:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-slate-600">Let’s talk</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em]">Ready when you are.</h2><p className="mt-4 max-w-lg leading-7 text-slate-600">{content.contactPrompt}</p></div><div className="rounded-xl bg-white p-6 shadow-sm"><p className="font-semibold">{business.callToAction}</p><div className="mt-4 flex flex-col gap-2 text-sm text-slate-600"><a className="hover:text-slate-950" href={phoneHref}>{business.phone}</a><a className="hover:text-slate-950" href={emailHref}>{business.email}</a><p>{business.serviceArea}</p></div></div></div></section>
    <footer className="border-t border-slate-200 px-5 py-7 text-center text-sm text-slate-500">© {new Date().getFullYear()} {business.businessName}. All rights reserved.</footer>
    {aiContent && <section className="mx-auto max-w-6xl px-5 py-18 sm:px-8"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-slate-500">Questions, answered</p><div className="mt-6 grid gap-4 md:grid-cols-2">{aiContent.faq.map((item) => <div className="rounded-xl border border-slate-200 p-5" key={item.question}><h3 className="font-semibold">{item.question}</h3><p className="mt-2 leading-6 text-slate-600">{item.answer}</p></div>)}</div></section>}
  </article>;
}
