/* eslint-disable @next/next/no-img-element -- Project media is user-configured external media. */
import type React from "react";
import { defaultSiteSettings, type SiteSectionId, type WebsiteProject } from "@/lib/website-types";

const styles = { Modern: { card: "bg-cyan-50", surface: "bg-slate-950", button: "bg-cyan-400 text-slate-950" }, Bold: { card: "bg-orange-50", surface: "bg-orange-500", button: "bg-orange-500 text-white" }, Professional: { card: "bg-blue-50", surface: "bg-blue-950", button: "bg-blue-700 text-white" }, Friendly: { card: "bg-lime-50", surface: "bg-emerald-950", button: "bg-lime-400 text-slate-950" }, Minimal: { card: "bg-stone-100", surface: "bg-stone-900", button: "bg-stone-900 text-white" } } as const;
function safe(url: string) { try { const parsed = new URL(url); return parsed.protocol === "https:" || parsed.protocol === "http:" ? url : null; } catch { return null; } }
export function SiteRenderer({ project }: { project: WebsiteProject }) {
  const ai = project.generatedContent; const content = ai ? { tagline: ai.tagline, hero: ai.hero, services: ai.services, about: ai.about, benefits: ai.benefits, faq: ai.faq, contact: ai.contact } : { tagline: project.content.tagline, hero: { headline: project.content.heroHeading, supportingText: project.content.heroDescription, primaryCTA: project.business.callToAction }, services: project.content.services, about: { heading: "About us", body: project.content.about }, benefits: project.content.benefits, faq: [], contact: { heading: "Ready when you are", body: project.content.contactPrompt } };
  const theme = styles[project.visualStyle]; const settings = project.siteSettings ?? defaultSiteSettings; const design = settings.theme; const layout = settings.layoutFamily; const hidden = new Set(settings.hiddenSections); const photo = project.workSamples.find((sample) => sample.mediaType === "IMAGE" && safe(sample.mediaUrl)); const contrast = (color: string) => Number.parseInt(color.slice(1, 3), 16) * 0.299 + Number.parseInt(color.slice(3, 5), 16) * 0.587 + Number.parseInt(color.slice(5, 7), 16) * 0.114 > 160 ? "#111827" : "#ffffff"; const foreground = contrast(design.primaryColor); const accentForeground = contrast(design.accentColor); const radius = design.buttonStyle === "Square" ? "0.125rem" : design.buttonStyle === "Soft" ? "0.75rem" : "9999px"; const spacing = design.spacingDensity === "Compact" ? "3rem" : design.spacingDensity === "Spacious" ? "6rem" : "4rem"; const fontClass = design.fontPair === "Classic" ? "font-serif" : design.fontPair === "Friendly" ? "font-sans" : design.fontPair === "Bold" ? "font-mono" : "font-sans";
  const section: Record<SiteSectionId, React.ReactNode> = {
    hero: <section className={`${theme.card} border-y`} key="hero"><div className={`mx-auto grid max-w-6xl gap-8 px-5 sm:px-8 ${design.heroStyle === "Visual" || layout === "Showcase" && photo ? "lg:grid-cols-2 lg:items-center" : design.heroStyle === "Text Focus" ? "max-w-4xl" : "lg:grid-cols-[1.2fr_.8fr]"}`} style={{ paddingTop: spacing, paddingBottom: spacing }}><div><p className="text-sm font-semibold uppercase tracking-widest text-slate-500">{content.tagline}</p><h1 className={`mt-5 font-semibold tracking-tight ${design.heroStyle === "Visual" || layout === "Showcase" ? "text-5xl sm:text-7xl" : "text-4xl sm:text-6xl"}`}>{content.hero.headline}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">{content.hero.supportingText}</p><a className="mt-8 inline-block px-5 py-3 text-sm font-semibold" href="#contact" style={{ backgroundColor: design.primaryColor, color: foreground, borderRadius: radius }}>{content.hero.primaryCTA}</a></div>{design.heroStyle !== "Text Focus" && photo ? <img alt={photo.title} className="aspect-[4/3] w-full rounded-2xl object-cover shadow-xl" src={photo.mediaUrl} /> : design.heroStyle !== "Text Focus" ? <div className={`${theme.surface} rounded-2xl p-8 text-white`}><p className="text-sm uppercase tracking-widest text-white/60">Local expertise</p><p className="mt-6 text-2xl font-semibold">Built around your needs.</p><p className="mt-4 text-white/70">Serving {project.business.serviceArea} with care and clarity.</p></div> : null}</div></section>,
    services: <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8" key="services"><p className="inline-block rounded-full px-3 py-1 text-sm font-semibold uppercase tracking-widest" style={{ backgroundColor: design.accentColor, color: accentForeground }}>What we do</p><h2 className="mt-3 text-3xl font-semibold">Services designed around you.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{content.services.map((item) => <article className="rounded-xl border p-5" key={item.name}><span className="mb-3 block h-1 w-10 rounded-full" style={{ backgroundColor: design.accentColor }} /><h3 className="font-semibold">{item.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p></article>)}</div></section>,
    about: <section className="border-y bg-slate-50" key="about"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:px-8 lg:grid-cols-2"><h2 className="text-3xl font-semibold">{content.about.heading}</h2><p className="text-lg leading-8 text-slate-600">{content.about.body}</p></div></section>,
    benefits: <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8" key="benefits"><div className={`${theme.surface} rounded-2xl p-8 text-white`}><p className="text-sm uppercase tracking-widest text-white/60">Why choose us</p><div className="mt-6 grid gap-4 md:grid-cols-3">{content.benefits.map((item) => <p key={item}>{item}</p>)}</div></div></section>,
    work: project.workSamples.length ? <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8" key="work"><p className="text-sm font-semibold uppercase tracking-widest text-slate-500">Our work</p><h2 className="mt-3 text-3xl font-semibold">A look at what we do.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{project.workSamples.map((sample) => <article className="overflow-hidden rounded-xl border" key={sample.id}>{sample.mediaType === "IMAGE" && safe(sample.mediaUrl) ? <img alt={sample.title} className="aspect-[4/3] w-full object-cover" src={sample.mediaUrl} /> : <div className="aspect-[4/3] bg-slate-100" />}<div className="p-4"><h3 className="font-semibold">{sample.title}</h3>{sample.description && <p className="mt-1 text-sm text-slate-600">{sample.description}</p>}</div></article>)}</div></section> : null,
    testimonials: project.testimonials.length ? <section className={`${theme.card} border-y`} key="testimonials"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><p className="text-sm font-semibold uppercase tracking-widest text-slate-500">Customer feedback</p><div className="mt-7 grid gap-4 md:grid-cols-2">{project.testimonials.map((item) => <blockquote className="rounded-xl bg-white p-6" key={item.id}>“{item.testimonialText}”<footer className="mt-4 text-sm font-semibold">{item.customerName}</footer></blockquote>)}</div></div></section> : null,
    faq: content.faq.length ? <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8" key="faq"><p className="text-sm font-semibold uppercase tracking-widest text-slate-500">Questions, answered</p><div className="mt-7 grid gap-4 md:grid-cols-2">{content.faq.map((item) => <article className="rounded-xl border p-5" key={item.question}><h3 className="font-semibold">{item.question}</h3><p className="mt-2 text-slate-600">{item.answer}</p></article>)}</div></section> : null,
    contact: <section className={`${theme.card}`} id="contact" key="contact"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:px-8 lg:grid-cols-2"><div><h2 className="text-3xl font-semibold">{content.contact.heading}</h2><p className="mt-4 text-slate-600">{content.contact.body}</p></div><div className="rounded-xl bg-white p-6"><p className="font-semibold">{project.business.callToAction}</p><p className="mt-3 text-sm"><a className="underline" href={`tel:${project.business.phone.replace(/[^+0-9]/g, "")}`}>{project.business.phone}</a><br /><a className="underline" href={`mailto:${project.business.email}`}>{project.business.email}</a><br />{project.business.serviceArea}</p></div></div></section>
  };
  const layoutOrder: SiteSectionId[] = layout === "Classic" ? ["hero", "services", "about", "benefits", "work", "testimonials", "faq", "contact"] : layout === "Conversion" ? ["hero", "benefits", "services", "testimonials", "work", "about", "faq", "contact"] : ["hero", "work", "about", "services", "testimonials", "benefits", "faq", "contact"];
  const order = settings.sectionOrder.join() === defaultSiteSettings.sectionOrder.join() ? layoutOrder : settings.sectionOrder;
  const backgroundForeground = design.autoContrast ? contrast(design.backgroundColor) : design.textColor; const canvasColor = design.backgroundStyle === "Dark" ? "#111827" : design.backgroundStyle === "Soft" ? design.accentColor : design.backgroundColor;
  return <article className={`overflow-hidden ${fontClass}`} style={{ backgroundColor: canvasColor, color: backgroundForeground, "--site-primary": design.primaryColor, "--site-accent": design.accentColor, "--site-background": design.backgroundColor } as React.CSSProperties}><header className="mx-auto flex max-w-6xl justify-between px-5 py-5 sm:px-8">{design.logoUrl ? <img alt={`${project.business.businessName} logo`} className="h-10 max-w-48 object-contain" src={design.logoUrl} /> : <p className="font-bold">{project.business.businessName}</p>}<a href="#contact">Contact</a></header>{layout === "Conversion" && <div className="px-5 py-3 text-center text-sm font-semibold" style={{ backgroundColor: design.primaryColor, color: foreground }}>Clear communication · Local service · {project.business.callToAction}</div>}{order.map((id) => hidden.has(id) ? null : section[id])}<footer className="border-t px-5 py-7 text-center text-sm" style={{ color: backgroundForeground }}>{design.logoUrl ? <img alt="" className="mx-auto mb-3 h-8 max-w-36 object-contain" src={design.logoUrl} /> : null}© {new Date().getFullYear()} {project.business.businessName}</footer></article>;
}
