/* eslint-disable @next/next/no-img-element -- Project media is user-configured external media. */
import type React from "react";
import { defaultSiteSettings, type SiteSectionId } from "@/lib/website-types";
import type { PublicSite } from "@/lib/public-site";
import { borderColor, contrastRatio, readableForeground } from "@/lib/theme-colors";

function safe(url: string) { try { const parsed = new URL(url); return parsed.protocol === "https:" || parsed.protocol === "http:" ? url : null; } catch { return null; } }

export function SiteRenderer({ project }: { project: Omit<PublicSite, "siteSettings"> & { siteSettings?: PublicSite["siteSettings"] } }) {
  const settings = project.siteSettings ?? defaultSiteSettings;
  const design = settings.theme;
  const ai = project.generatedContent;
  const content = ai ? { tagline: ai.tagline, hero: ai.hero, services: ai.services, about: ai.about, benefits: ai.benefits, faq: ai.faq, contact: ai.contact } : { tagline: project.content.tagline, hero: { headline: project.content.heroHeading, supportingText: project.content.heroDescription, primaryCTA: project.business.callToAction }, services: project.content.services, about: { heading: "About us", body: project.content.about }, benefits: project.content.benefits, faq: [], contact: { heading: "Ready when you are", body: project.content.contactPrompt } };
  const photo = project.workSamples.find((sample) => sample.mediaType === "IMAGE" && safe(sample.mediaUrl));
  const radius = design.buttonStyle === "Square" ? "0.125rem" : design.buttonStyle === "Soft" ? "0.75rem" : "9999px";
  const spacing = design.spacingDensity === "Compact" ? "3rem" : design.spacingDensity === "Spacious" ? "6rem" : "4rem";
  const fontClass = design.fontPair === "Classic" ? "font-serif" : design.fontPair === "Bold" ? "font-mono" : "font-sans";
  const on = (background: string, preferred = design.textColor) => readableForeground(background, preferred, design.autoContrast);
  const surface = (background: string): React.CSSProperties => ({ backgroundColor: background, color: on(background, design.bodyTextColor), borderColor: borderColor(background), "--heading-text": on(background, design.textColor), "--body-text": on(background, design.bodyTextColor), "--muted-text": on(background, design.mutedTextColor), "--primary-text": on(background, design.primaryColor) } as React.CSSProperties);
  const card = surface(design.cardColor);
  const page = surface(design.backgroundColor);
  const sectionSurface = surface(design.surfaceColor);
  const primaryText = readableForeground(design.primaryColor, "#ffffff", true);
  const accentText = readableForeground(design.accentColor, design.textColor, true);
  const primaryButton: React.CSSProperties = { backgroundColor: "var(--primary)", color: "var(--primary-foreground)", borderRadius: radius, boxShadow: contrastRatio(design.primaryColor, design.backgroundColor) < 3 ? "inset 0 0 0 1px var(--primary-foreground)" : undefined };
  const accentLabel: React.CSSProperties = { backgroundColor: "var(--accent)", color: "var(--accent-foreground)", borderRadius: radius };
  const sectionPadding = { paddingTop: spacing, paddingBottom: spacing };
  const heading = "font-semibold tracking-tight";
  const body = "leading-7";
  const muted = "text-sm font-semibold uppercase tracking-widest";
  const hidden = new Set(settings.hiddenSections);

  const section: Record<SiteSectionId, React.ReactNode> = {
    hero: <section className="border-y" key="hero" style={page}><div className={`mx-auto grid max-w-6xl gap-8 px-5 sm:px-8 ${design.heroStyle === "Visual" || settings.layoutFamily === "Showcase" && photo ? "lg:grid-cols-2 lg:items-center" : design.heroStyle === "Text Focus" ? "max-w-4xl" : "lg:grid-cols-[1.2fr_.8fr]"}`} style={{ ...page, ...sectionPadding }}><div><p className={muted} style={{ color: "var(--primary-text)" }}>{content.tagline}</p><h1 className={`mt-5 ${heading} ${design.heroStyle === "Visual" || settings.layoutFamily === "Showcase" ? "text-5xl sm:text-7xl" : "text-4xl sm:text-6xl"}`} style={{ color: "var(--heading-text)" }}>{content.hero.headline}</h1><p className={`mt-5 max-w-xl text-lg ${body}`} style={{ color: "var(--body-text)" }}>{content.hero.supportingText}</p><a className="mt-8 inline-block px-5 py-3 text-sm font-semibold" href="#contact" style={primaryButton}>{content.hero.primaryCTA}</a></div>{design.heroStyle !== "Text Focus" && photo ? <img alt={photo.title} className="aspect-[4/3] w-full rounded-2xl object-cover shadow-xl" src={photo.mediaUrl} /> : design.heroStyle !== "Text Focus" ? <div className="rounded-2xl p-8" style={sectionSurface}><p className={muted} style={{ color: "var(--primary-text)" }}>Local expertise</p><p className="mt-6 text-2xl font-semibold" style={{ color: "var(--heading-text)" }}>Built around your needs.</p><p className={`mt-4 ${body}`} style={{ color: "var(--body-text)" }}>Serving {project.business.serviceArea} with care and clarity.</p></div> : null}</div></section>,
    services: <section className="mx-auto max-w-6xl px-5 sm:px-8" key="services" style={{ ...page, ...sectionPadding }}><p className={`inline-block px-3 py-1 ${muted}`} style={accentLabel}>What we do</p><h2 className={`mt-3 text-3xl ${heading}`} style={{ color: "var(--heading-text)" }}>Services designed around you.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{content.services.map((item) => <article className="rounded-xl border p-5" key={item.name} style={card}><span className="mb-3 block h-1 w-10 rounded-full" style={{ backgroundColor: "var(--accent)" }} /><h3 className={heading} style={{ color: "var(--heading-text)" }}>{item.name}</h3><p className="mt-2 text-sm leading-6" style={{ color: "var(--body-text)" }}>{item.description}</p></article>)}</div></section>,
    about: <section className="border-y" key="about" style={sectionSurface}><div className="mx-auto grid max-w-6xl gap-8 px-5 sm:px-8 lg:grid-cols-2" style={sectionPadding}><h2 className={`text-3xl ${heading}`} style={{ color: "var(--heading-text)" }}>{content.about.heading}</h2><p className={`text-lg ${body}`} style={{ color: "var(--body-text)" }}>{content.about.body}</p></div></section>,
    benefits: <section className="mx-auto max-w-6xl px-5 sm:px-8" key="benefits" style={{ ...page, ...sectionPadding }}><div className="rounded-2xl border p-8" style={sectionSurface}><p className={muted} style={{ color: "var(--primary-text)" }}>Why choose us</p><div className="mt-6 grid gap-4 md:grid-cols-3">{content.benefits.map((item) => <p className={body} key={item} style={{ color: "var(--body-text)" }}>{item}</p>)}</div></div></section>,
    work: project.workSamples.length ? <section className="mx-auto max-w-6xl px-5 sm:px-8" key="work" style={{ ...page, ...sectionPadding }}><p className={muted} style={{ color: "var(--primary-text)" }}>Our work</p><h2 className={`mt-3 text-3xl ${heading}`} style={{ color: "var(--heading-text)" }}>A look at what we do.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{project.workSamples.map((sample) => <article className="overflow-hidden rounded-xl border" key={sample.id} style={card}>{sample.mediaType === "IMAGE" && safe(sample.mediaUrl) ? <img alt={sample.title} className="aspect-[4/3] w-full object-cover" src={sample.mediaUrl} /> : sample.mediaType === "VIDEO" && safe(sample.mediaUrl) ? <video aria-label={sample.title} className="aspect-[4/3] w-full object-contain" controls playsInline preload="metadata" src={sample.mediaUrl} /> : <div className="aspect-[4/3]" style={sectionSurface} />}<div className="p-4"><h3 className={heading} style={{ color: "var(--heading-text)" }}>{sample.title}</h3>{sample.description && <p className="mt-1 text-sm" style={{ color: "var(--body-text)" }}>{sample.description}</p>}</div></article>)}</div></section> : null,
    testimonials: project.testimonials.length ? <section className="border-y" key="testimonials" style={sectionSurface}><div className="mx-auto max-w-6xl px-5 sm:px-8" style={sectionPadding}><p className={muted} style={{ color: "var(--primary-text)" }}>Customer feedback</p><div className="mt-7 grid gap-4 md:grid-cols-2">{project.testimonials.map((item) => <blockquote className="rounded-xl border p-6" key={item.id} style={card}><span className="text-3xl" style={{ color: "var(--accent)" }}>“</span><p className={body} style={{ color: "var(--body-text)" }}>{item.testimonialText}</p><footer className="mt-4 text-sm font-semibold" style={{ color: "var(--heading-text)" }}>{item.customerName}</footer></blockquote>)}</div></div></section> : null,
    faq: content.faq.length ? <section className="mx-auto max-w-6xl px-5 sm:px-8" key="faq" style={{ ...page, ...sectionPadding }}><p className={muted} style={{ color: "var(--primary-text)" }}>Questions, answered</p><div className="mt-7 grid gap-4 md:grid-cols-2">{content.faq.map((item) => <article className="rounded-xl border p-5" key={item.question} style={card}><h3 className={heading} style={{ color: "var(--heading-text)" }}>{item.question}</h3><p className={`mt-2 ${body}`} style={{ color: "var(--body-text)" }}>{item.answer}</p></article>)}</div></section> : null,
    contact: <section id="contact" key="contact" style={sectionSurface}><div className="mx-auto grid max-w-6xl gap-8 px-5 sm:px-8 lg:grid-cols-2" style={sectionPadding}><div><h2 className={`text-3xl ${heading}`} style={{ color: "var(--heading-text)" }}>{content.contact.heading}</h2><p className={`mt-4 ${body}`} style={{ color: "var(--body-text)" }}>{content.contact.body}</p></div><div className="rounded-xl border p-6" style={card}><p className="font-semibold" style={{ color: "var(--heading-text)" }}>{project.business.callToAction}</p><p className="mt-3 text-sm" style={{ color: "var(--body-text)" }}>{project.business.phone && <><a className="underline" href={`tel:${project.business.phone.replace(/[^+0-9]/g, "")}`}>{project.business.phone}</a><br /></>}{project.business.email && <><a className="underline" href={`mailto:${project.business.email}`}>{project.business.email}</a><br /></>}{project.business.serviceArea}</p></div></div></section>,
  };
  const layoutOrder: SiteSectionId[] = settings.layoutFamily === "Classic" ? ["hero", "services", "about", "benefits", "work", "testimonials", "faq", "contact"] : settings.layoutFamily === "Conversion" ? ["hero", "benefits", "services", "testimonials", "work", "about", "faq", "contact"] : ["hero", "work", "about", "services", "testimonials", "benefits", "faq", "contact"];
  const order = settings.sectionOrder.join() === defaultSiteSettings.sectionOrder.join() ? layoutOrder : settings.sectionOrder;
  const tokens = { ...page, "--site-bg": design.backgroundColor, "--surface-bg": design.surfaceColor, "--card-bg": design.cardColor, "--primary": design.primaryColor, "--primary-foreground": primaryText, "--accent": design.accentColor, "--accent-foreground": accentText, "--heading-text": on(design.backgroundColor, design.textColor), "--body-text": on(design.backgroundColor, design.bodyTextColor), "--muted-text": on(design.backgroundColor, design.mutedTextColor), "--border-color": borderColor(design.backgroundColor) } as React.CSSProperties;
  return <article className={`overflow-hidden [overflow-wrap:anywhere] ${fontClass}`} style={tokens}><header className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-5 py-5 sm:px-8" style={page}>{design.logoUrl && safe(design.logoUrl) ? <img alt={`${project.business.businessName} logo`} className="h-10 max-w-48 object-contain" src={design.logoUrl} /> : <p className="font-bold" style={{ color: "var(--heading-text)" }}>{project.business.businessName}</p>}<a className="font-semibold" href="#contact" style={{ color: "var(--primary-text)" }}>Contact</a></header>{settings.layoutFamily === "Conversion" && <div className="px-5 py-3 text-center text-sm font-semibold" style={primaryButton}>Clear communication · Local service · {project.business.callToAction}</div>}{order.map((id) => hidden.has(id) ? null : section[id])}<footer className="border-t px-5 py-7 text-center text-sm" style={page}>{design.logoUrl && safe(design.logoUrl) ? <img alt="" className="mx-auto mb-3 h-8 max-w-36 object-contain" src={design.logoUrl} /> : null}© {new Date().getFullYear()} {project.business.businessName}</footer></article>;
}
