import Link from "next/link";
import { listAdminProjects } from "@/lib/project-repository";

export const dynamic = "force-dynamic";

export default async function AdminProjectsPage({ searchParams }: { searchParams: Promise<{ filter?: string }> }) {
  const { filter } = await searchParams;
  const projects = await listAdminProjects();
  const filtered = projects.filter((project) => filter === "demos" ? project.isDemo : filter === "featured" ? project.featuredBusiness?.enabled : true);
  return <section className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><div className="flex items-end justify-between gap-4"><div><Link className="text-sm font-semibold text-slate-600" href="/admin">Back to admin</Link><p className="mt-6 eyebrow">Projects</p><h1 className="mt-4 text-4xl font-semibold">Manage sites</h1></div><Link className="rounded-full bg-slate-900 px-5 py-3 text-sm font-semibold text-white" href="/admin/projects/new">Create sample site</Link></div><div className="mt-8 grid gap-4 md:grid-cols-2">{filtered.map((project) => <article className="rounded-2xl border p-6" key={project.id}><div className="flex flex-wrap gap-2"><h2 className="text-xl font-semibold">{project.businessName}</h2>{project.isDemo && <span className="rounded-full bg-lime-100 px-2 py-1 text-xs font-semibold text-lime-800">Demo</span>}{project.featuredBusiness?.enabled && <span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-800">Featured business</span>}</div><p className="mt-1 text-sm text-slate-600">{project.businessType}</p><p className="mt-5 text-sm text-slate-500">Updated {project.updatedAt.toLocaleDateString()} · {project.userId ? "Owned project" : "Unassigned sample"}</p><p className="mt-3 text-sm">{project.isPublished ? "Published" : "Unpublished"}{project.publicSlug && <> | /site/{project.publicSlug}</>}{project.publishedAt && <> | First published {project.publishedAt.toLocaleDateString()}</>}</p><div className="mt-5 flex gap-4"><Link className="text-sm font-semibold" href={`/dashboard/projects/${project.id}`}>Manage project</Link><Link className="text-sm font-semibold" href={`/dashboard/projects/${project.id}/preview`}>Preview</Link></div></article>)}</div>{filtered.length === 0 && <p className="mt-8 rounded-xl border border-dashed p-6 text-slate-600">No matching projects yet.</p>}</section>;
}
